TMS/Controllers/BatchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TMS.Interface;
using TMS.Models;

namespace TMS.Controllers
{
    public class BatchController : Controller
    {
        
            IBatch _repo;
            ICourse _repo1;
            public BatchController(IBatch repo, ICourse repo1)
            {
                _repo = repo;
                _repo1 = repo1;
            }
            public IActionResult Index()
            {
                return View(_repo.GetBatches());
            }
            public IActionResult Details(int id)
            {
                return View(_repo.GetBatchById(id));
            }
            public IActionResult Edit(int id)
            {
            ViewData["Courses"] = new SelectList(_repo1.GetCourses(), "CourseId", "CourseName");
            Batch obj = _repo.GetBatchById(id);
                return View(obj);
            }
            [HttpPost]
            public IActionResult Edit(int id, Batch batch)
            {
                _repo.Edit(id, batch);
                return RedirectToAction("index");
            }
            public IActionResult Create()
            {
                ViewData["Courses"] = new SelectList(_repo1.GetCourses(), "CourseId", "CourseName");

                return View();
            }
            [HttpPost]
            public IActionResult Create(Batch batch)
            {
                _repo.Create(batch);
                return RedirectToAction("index");
            }

        }
    }

TMS/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using TMS.Interface;
using TMS.Models;

namespace TMS.Controllers
{
    public class CourseController : Controller
    {



        ICourse _repo;
        public CourseController(ICourse repo)
        {
            _repo = repo;
        }





        public IActionResult Index()
        {
            return View(_repo.GetCourses());
        }
        public IActionResult Details(int id)
        {
            return View(_repo.GetCourseById(id));
        }
        public IActionResult Delete(int id)
        {
            Course obj = _repo.GetCourseById(id);
            return View(obj);
        }





        [HttpPost]
        public IActionResult Deleted(int CourseId)
        {
            _repo.Delete(CourseId);
            return RedirectToAction("index");
        }





        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Course course)
        {



            var t = _repo.GetCourses();
            _repo.Create(course);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            Course obj2 = _repo.GetCourseById(id);
            return View(obj2);
        }
        [HttpPost]
        public IActionResult Edit(int id, Course course)
        {
            _repo.Edit(id, course);
            return RedirectToAction("index");
        }
    }
}

TMS/Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TMS.Context;
using TMS.Interface;
using TMS.Models;

namespace TMS.Controllers
{
    public class RequestController : Controller
    {
        private readonly MyDBContext _db;
        private readonly IRequest _irq;
        private readonly IUser _user;
        private readonly IBatch _batch;

        public RequestController(MyDBContext db, IRequest irq, IBatch batch, IUser user)
        {
            _user = user;
            _batch = batch;
            _db = db;
            _irq = irq;
        }

        public IActionResult Index()
        {
            return View(_irq.GetReqData());
        }

        public IActionResult IndexManager()
        {
            return View(_irq.GetReqData());
        }

        public IActionResult IndexE()
        {
            return View(_irq.GetReqData());
        }

        public IActionResult IndexEmployee()
        {
            ViewData["Batches"] = new SelectList(_batch.GetBatch(), "BatchId", "BatchName");
            ViewData["Users"] = new SelectList(_user.GetUser(), "UId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult IndexEmployee(Request request)
        {
            _irq.Create(request);
            return RedirectToAction("IndexE");
        }

        public IActionResult Create()
        {
            ViewData["Batches"] = new SelectList(_batch.GetBatch(), "BatchId", "BatchName");
            ViewData["Users"] = new SelectList(_user.GetUser(), "UId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Request request)
        { 
               _irq.Create(request);
            return RedirectToAction("Index");
        }

        public IActionResult Accept(int id)
        {
            _irq.Accept(id);
            return RedirectToAction("Index");
        }

        public IActionResult Reject(int id)
        {
            _irq.Reject(id);
            return RedirectToAction("Index");
        }

        public IActionResult Set()
        {
            return View();
        }

    }
}

TMS/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMS.Context;
using TMS.Interface;
using TMS.Models;

namespace TMS.Controllers
{
    public class UserController : Controller
    {
        IUser _user;
        MyDBContext _dbContext;

        public UserController(IUser user,MyDBContext dbContext)
        {
            _user = user;
            _dbContext = dbContext;
        }

      
        public IActionResult Index()
        {

            //ViewBag.Roles = new SelectList(Enum.GetValues(typeof(Role)));

            //ViewData["ManagerId"] = new SelectList(_dbContext.Users.Where(x => (int)x.RoleName == 1), "Id", "UName");
            return View(_user.GetUserV());
        }

        public IActionResult Create()
        {
            //  ViewBag.Roles = new SelectList(Enum.GetValues(typeof(Role)));
            ViewData["ManagerId"] = new SelectList(_dbContext.Users.Where(x => (int)x.RoleName == 1), "UId", "Name", null);
            return View();
           
        }

        [HttpPost]
        public IActionResult Create(User user)
        {
             _user.Create(user);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            User obj = _user.GetUserById(id);
            return View(obj);
        }
        [HttpPost]
        public IActionResult Deleted(int UId)
        {
            User obj = _user.GetUserById(UId);
            if (obj != null)
                _user.Delete(obj.UId);
            return RedirectToAction("Index");

        }
        public IActionResult Edit(int id)
        {
            User obj = _user.GetUserById(id);
            return View(obj);
        }
        [HttpPost]
        public IActionResult Edit(int id, User user)
        {
            User obj = _user.GetUserById(id);
            if (obj != null)
                _user.Edit(id, user);
            return RedirectToAction("Index");

        }
        public IActionResult Details(int id)
        {
            var user = _user.GetUserById(id);
            
            return View(user);
        }

        public IActionResult Validate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Validate(string Email, string Password)
        {
          var user =   _user.ValidateUser(Email, Password);
            if (user != null)
            {
                if ((int)user.RoleName == 0)
                {
                    return RedirectToAction("Emp");
                }
                else if ((int)user.RoleName == 1)
                {
                    return RedirectToAction("Manager");
                }
                else if ((int)user.RoleName == 3)
                {
                    return RedirectToAction("Admin");
                }
                return RedirectToAction("Index");
            }
            else {
                return RedirectToAction("Validate");
            }
         }

        public IActionResult Emp()
        {
            return View();
        }

        public IActionResult Manager()
        {
            return View();
        }

        public IActionResult Admin()
        {
            return View();
        }

        public IActionResult Logoutt()
        {
            return RedirectToAction("Validate");
        }

    }
}

TMS/Views/Shared/EmpLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

TMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TMS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users List</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Validate"> Validate </a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Batch" asp-action="Index"> Batches </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index"> Courses </a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index"> Request </a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>